---
# Não deixe um grupo vazio se não irá substituir tudo
# Consulte configuração em node_modules/@agtm/node-framework/*.yaml

# NF-MANAGER must not run directly, it must be loaded in another project

httpServer:
  enabled: false

jobManager:
  enabled: false

monitor:
  enabled: false

socket:
  enabled: false

resourceMonitor:
  enabled: false