---
# Não deixe um grupo vazio se não irá substituir tudo
# Consulte configuração em node_modules/@agtm/node-framework/*.yaml
monitor:
  enabled: false
logger:
  console:
    enabled: true
    handleExceptions: true

httpServer:
  hostname: '127.0.0.1'
  port: 3002

socket:
  port: 4002